<?php

namespace GeoServices;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-10 at 21:27:34.
 */
class GeoExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var GeoException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GeoException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testTest() {
        $this->assertTrue(true);
    }

}
