<?php

namespace GeoServices;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-10 at 20:58:28.
 */
class GeoObjectTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var GeoObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GeoObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GeoServices\GeoObject::getProperties
     */
    public function testGetProperties() {
        $this->assertInternalType('array', $this->object->getProperties());
        $fields = array('countryName','city','latitude','longitude','zip','regionName','countryCode','isp');
        foreach($fields as $f){
            $this->assertContains($f, $this->object->getProperties());
        }
        
    }

}
