<?php

namespace GeoServices;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-10 at 20:58:27.
 */
class GeoServiceTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var GeoService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GeoService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GeoServices\GeoService::setMaxmindDb
     * @todo   Implement testSetMaxmindDb().
     */
    public function testSetMaxmindDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GeoServices\GeoService::setMaxmindISPDb
     * @todo   Implement testSetMaxmindISPDb().
     */
    public function testSetMaxmindISPDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GeoServices\GeoService::setMaxmindOldDb
     * @todo   Implement testSetMaxmindOldDb().
     */
    public function testSetMaxmindOldDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GeoServices\GeoService::lookup
     * @todo   Implement testLookup().
     */
    public function testLookup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GeoServices\GeoService::getCallStack
     * @todo   Implement testGetCallStack().
     */
    public function testGetCallStack() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
