<?php

namespace GeoServices\Services;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-10 at 20:58:27.
 */
class IpgeobaseruTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Ipgeobaseru
     */
    protected $object;
    private $cidr = '/var/www/geostuff/data/www/ipservice.loc/vendor/kubrey/ipgeobase/src/etc/cidr_optim.txt';
    private $cities = '/var/www/geostuff/data/www/ipservice.loc/vendor/kubrey/ipgeobase/src/etc/cities.txt';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Ipgeobaseru;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

   /**
     * @expectedException GeoServices\GeoException
     */
    public function testInvalidIpException() {
        $this->object->lookup('1.2.3');
    }

    public function testNonExistingCountryDb() {
        $this->assertFileExists($this->cidr, "No country file for ipgeobase");
    }
    
    public function testNonExistingCityDb() {
        $this->assertFileExists($this->cities, "No cities file for ipgeobase");
    }

    public function testValidReturn() {
        $ip = '78.109.16.159';//нужен российский ip
        $this->assertInstanceOf('GeoServices\GeoObject', $this->object->lookup($ip), 'Return wrong instance');
    }

}
