<?php

namespace GeoServices\Services;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-10 at 20:58:27.
 */
class MaxmindTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Maxmind
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Maxmind;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @expectedException \GeoServices\GeoException
     */
    public function testInvalidIpException() {
        $this->object->lookup('1.2.3');
    }

    /**
     * @expectedException \GeoServices\GeoException
     */
    public function testNonExistingDb() {
        $db = 'maxminddb.mmdb';
        $this->object->lookup('1.1.1.1', array('maxminddb' => $db));
    }

    public function testDbExists() {
        $dbReal = '/var/www/GeoLite2-City.mmdb';
        $this->assertFileExists($dbReal, 'Maxmind mmdb file does not exist');
    }

    public function testValidReturn() {
        $dbReal = '/var/www/GeoLite2-City.mmdb';
        $this->assertInstanceOf('GeoServices\GeoObject', $this->object->lookup('1.1.1.1', array('maxminddb' => $dbReal)), 'Return wrong instance');
    }

}
