<?php

namespace GeoServices\Services;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-10 at 20:58:28.
 */
class TelizeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Telize
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Telize;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @expectedException \GeoServices\GeoException
     */
    public function testInvalidIpException() {
        $this->object->lookup('1.2.3');
    }

    public function testValidReturn() {
//        $this->assertInstanceOf('GeoServices\GeoObject', $this->object->lookup('100.100.100.100'), 'Return wrong instance');
    }

}
